* Matthew Blount
I'm a software developer in Brooklyn, New York. I'm working on a
project called [[https://github.com/xkapastel/denshi][Denshi]], a development environment that incorporates
modern research in programming languages and machine learning.

[[https://twitter.com/xkapastel][Twitter]] - [[https://github.com/xkapastel][GitHub]] - [[https://liberapay.com/xkapastel][Liberapay]]

** Writing
- [[./essays/dialect.org][Dialects in Denshi]]
Mutually intelligible domain specific languages: they share a common
denotational (computability) semantics, but differ in their
operational (complexity) semantics.

** Reading
Some interesting things I've read, sometimes with notes.

- [[https://arxiv.org/abs/1801.03526][Neural Program Synthesis with Priority Queue Training]]

An interesting result in neural program synthesis: it's feasible to
"bootstrap" a random neural network in to solving simple problems by
training it with its own output. [[./notes/pqt.org][(Notes)]]

- [[https://dl.acm.org/citation.cfm?id=3205597&dl=ACM&coll=DL][Learning an evolvable genotype-phenotype mapping]]

Using autoencoders to learn genotypes. [[./notes/automap.org][(Notes)]]

- [[http://www.jmlr.org/papers/volume18/15-631/15-631.pdf][Hinge-Loss Markov Random Fields and Probabilistic Soft Logic]]
  [[http://stephenbach.net/files/kimmig-probprog12.pdf][A Short Introduction to Probabilistic Soft Logic]]

A way to merge logical and statistical techniques for machine
learning. Looks a lot like a cleaned up and continuous version of the
Tsetlin machine. [[./notes/psl.org][(Notes)]]

- [[https://arxiv.org/abs/1804.01508][The Tsetlin Machine - A Game Theoretic Bandit Driven Approach to
  Optimal Pattern Recognition with Propositional Logic]]

A way to construct a neural net-like device with propositional
logic. [[./notes/tsetlin.org][(Notes)]]

- [[https://www.dreamsongs.com/Files/Incommensurability.pdf][The Structure of a Programming Language Revolution]]

A look at the competing paradigms of programming languages and
programming systems. [[./notes/revolution.org][(Notes)]]
